MyTact={}
MyTact[0]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_REACT,CAST_PASSIVE,PUSH_NEVER,DEBUFF_NEVER,CLASS_S,RESCUE_NEVER,-1,SNIPE_OK,KS_NEVER,1,CHASE_NORMAL} --Default
TactLastSavedDate        = "01/07/2023 23:37:28"