MyTact={}
MyTact[0]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_NEVER,CAST_REACT,PUSH_SELF,DEBUFF_NEVER,CLASS_BOTH,RESCUE_RETAINER,-1,SNIPE_OK,KS_NEVER,1,CHASE_NORMAL} --Default
TactLastSavedDate        = "01/07/2023 23:37:28"